fix

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -43,10 +43,31 @@ jobs:
         run: |
           curl -X POST -d {} "${{ env.DEPLOY_WEBHOOK_URL }}" -H "Content-Type:application/json"
 
-      # - name: Wait for Amplify to finish remote build
-      #   uses: duckbytes/amplify-build-status@v1.1
-      #   with:
-      #     app-id: ${{ env.AMPLIFY_APP_ID }}
-      #     branch-name: ${{ env.BRANCH }}
-      #     commit-id: ${{ github.sha }}
-      #     wait: true
+      - name: Wait for Amplify to finish remote build
+        run: |
+          APP_ID=${{ env.AMPLIFY_APP_ID }}
+
+          # Run initial command to get the status
+          OUTPUT=$(aws amplify get-app --app-id $APP_ID)
+          STATUS=$(echo $OUTPUT | jq -r '.app.productionBranch.status')
+
+          # Keep querying until status is RUNNING, PENDING, SUCCEED, or timeout after 10 minutes
+          ELAPSED=0
+          while [[ ("$STATUS" == "RUNNING" || "$STATUS" == "PENDING") && "$ELAPSED" -lt 600 ]]; do
+            sleep 10
+            ELAPSED=$((ELAPSED+10))
+            OUTPUT=$(aws amplify get-app --app-id $APP_ID)
+            STATUS=$(echo $OUTPUT | jq -r '.app.productionBranch.status')
+          done
+
+          # Check final status and exit with appropriate code
+          if [[ "$STATUS" == "SUCCEED" ]]; then
+            echo "Status: SUCCEED"
+            exit 0
+          elif [[ "$STATUS" == "FAILED" ]]; then
+            echo "Status: FAILED"
+            exit 1
+          else
+            echo "Status: TIMEOUT"
+            exit 1
+          fi
